name: 'JIRA properties labeler on Pull Request'
author: 'Xavier Serrat, forked and updated by Szymek Adach'
description: 'Label a Pull Request using JIRA issue properties'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  JIRA_URI:
    description: 'Jira URI of your organization'
    required: true
  JIRA_ENCODED_TOKEN:
    description: 'Jira encoded token to access to the Jira API'
    required: true
  regexp_jira_issue_code_on_pr_title:
    description: 'Regular expression to identify the JIRA issue code on a PR titlem e.g. ETS-12345'
    required: false
    default: '([A-Z]{3}-[0-9]{5}).*'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.JIRA_ENCODED_TOKEN }}
    - ${{ inputs.JIRA_URI }}
    - ${{ inputs.regexp_jira_issue_code_on_pr_title }}
branding:
  icon: 'tag'
  color: 'blue'
